name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Create and customize Flutter app
        run: |
          flutter create .
          echo 'import "package:flutter/material.dart";

          void main() {
            runApp(const MyApp());
          }

          class MyApp extends StatelessWidget {
            const MyApp({super.key});

            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                title: "Audio Amplifier v2",
                theme: ThemeData(
                  colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
                  useMaterial3: true,
                ),
                home: const MyHomePage(title: "Audio Amplifier v2"),
              );
            }
          }

          class MyHomePage extends StatefulWidget {
            const MyHomePage({super.key, required this.title});

            final String title;

            @override
            State<MyHomePage> createState() => _MyHomePageState();
          }

          class _MyHomePageState extends State<MyHomePage> {
            bool _isRunning = false;
            double _amplificationLevel = 0.5;
            double _mixLevel = 0.5;

            void _toggleAudio() {
              setState(() {
                _isRunning = !_isRunning;
              });
            }

            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(
                  backgroundColor: Theme.of(context).colorScheme.inversePrimary,
                  title: Text(widget.title),
                ),
                body: Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      Container(
                        width: 120,
                        height: 120,
                        margin: const EdgeInsets.all(20),
                        child: ElevatedButton(
                          onPressed: _toggleAudio,
                          style: ElevatedButton.styleFrom(
                            shape: const CircleBorder(),
                            backgroundColor: _isRunning ? Colors.red : Colors.green,
                          ),
                          child: Text(
                            _isRunning ? "OFF" : "ON",
                            style: const TextStyle(
                              fontSize: 24,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),
                      Text(
                        "Amplification: ${(_amplificationLevel * 100).round()}%",
                      ),
                      Slider(
                        value: _amplificationLevel,
                        onChanged: (value) {
                          setState(() {
                            _amplificationLevel = value;
                          });
                        },
                      ),
                      const SizedBox(height: 20),
                      Text(
                        "Mixage: ${(_mixLevel * 100).round()}%",
                      ),
                      Slider(
                        value: _mixLevel,
                        onChanged: (value) {
                          setState(() {
                            _mixLevel = value;
                          });
                        },
                      ),
                    ],
                  ),
                ),
              );
            }
          }' > lib/main.dart
      
      - name: Install dependencies
        run: flutter pub get
          
      - name: Build APK
        run: |
          flutter build apk --debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
