name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Create Flutter app in temp directory
        run: |
          mkdir -p /tmp/flutter_app
          cd /tmp/flutter_app
          flutter create --org com.example audio_app
          cp -r /tmp/flutter_app/audio_app/* $GITHUB_WORKSPACE/
          cp -r /tmp/flutter_app/audio_app/.* $GITHUB_WORKSPACE/ 2>/dev/null || true
      
      - name: Install dependencies
        run: flutter pub get
          
      - name: Build APK
        run: |
          flutter build apk --debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
