name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Create Flutter app and customize
        run: |
          mkdir -p /tmp/flutter_app
          cd /tmp/flutter_app
          flutter create --org com.example audio_app
          cp -r /tmp/flutter_app/audio_app/* $GITHUB_WORKSPACE/
          cp -r /tmp/flutter_app/audio_app/.* $GITHUB_WORKSPACE/ 2>/dev/null || true
          
          # Remplacer le contenu du fichier main.dart
          cat > $GITHUB_WORKSPACE/lib/main.dart << 'EOL'
          import 'package:flutter/material.dart';

          void main() {
            runApp(const AudioAmplifierApp());
          }

          class AudioAmplifierApp extends StatelessWidget {
            const AudioAmplifierApp({super.key});

            @override
            Widget build(BuildContext context) {
              return MaterialApp(
                title: 'Audio Amplifier',
                theme: ThemeData(
                  colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
                  useMaterial3: true,
                ),
                home: const AudioAmplifierHome(),
              );
            }
          }

          class AudioAmplifierHome extends StatefulWidget {
            const AudioAmplifierHome({super.key});

            @override
            State<AudioAmplifierHome> createState() => _AudioAmplifierHomeState();
          }

          class _AudioAmplifierHomeState extends State<AudioAmplifierHome> {
            bool _isRunning = false;
            double _amplificationLevel = 0.5;
            double _mixLevel = 0.5;
            double _morphingPosition = 0.5;

            void _toggleAudio() {
              setState(() {
                _isRunning = !_isRunning;
              });
            }

            void _updateMorphingPosition(double value) {
              setState(() {
                _morphingPosition = value;
              });
            }

            void _updateAmplification(double value) {
              setState(() {
                _amplificationLevel = value;
              });
            }

            void _updateMixLevel(double value) {
              setState(() {
                _mixLevel = value;
              });
            }

            String _getModeText() {
              if (_morphingPosition < 0.33) {
                return "Mode Ultra-rapide";
              } else if (_morphingPosition < 0.67) {
                return "Mode Équilibré";
              } else {
                return "Mode Haute Qualité";
              }
            }

            @override
            Widget build(BuildContext context) {
              return Scaffold(
                appBar: AppBar(
                  title: const Text('Audio Amplifier'),
                  backgroundColor: Theme.of(context).colorScheme.inversePrimary,
                ),
                body: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Column(
                    children: [
                      Container(
                        width: 120,
                        height: 120,
                        margin: const EdgeInsets.all(20),
                        child: ElevatedButton(
                          onPressed: _toggleAudio,
                          style: ElevatedButton.styleFrom(
                            shape: const CircleBorder(),
                            backgroundColor: _isRunning ? Colors.red : Colors.green,
                          ),
                          child: Text(
                            _isRunning ? 'OFF' : 'ON',
                            style: const TextStyle(
                              fontSize: 24,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),
                      Card(
                        child: Padding(
                          padding: const EdgeInsets.all(16.0),
                          child: Column(
                            children: [
                              Text(
                                _getModeText(),
                                style: Theme.of(context).textTheme.titleMedium,
                              ),
                              const SizedBox(height: 10),
                              Row(
                                children: [
                                  const Text('Ultra-rapide'),
                                  Expanded(
                                    child: Slider(
                                      value: _morphingPosition,
                                      onChanged: _updateMorphingPosition,
                                      divisions: 100,
                                    ),
                                  ),
                                  const Text('Haute Qualité'),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),
                      Card(
                        child: Padding(
                          padding: const EdgeInsets.all(16.0),
                          child: Column(
                            children: [
                              Text(
                                'Amplification: ${(_amplificationLevel * 100).round()}%',
                                style: Theme.of(context).textTheme.titleMedium,
                              ),
                              Slider(
                                value: _amplificationLevel,
                                onChanged: _updateAmplification,
                              ),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: 20),
                      Card(
                        child: Padding(
                          padding: const EdgeInsets.all(16.0),
                          child: Column(
                            children: [
                              Text(
                                'Mixage Ambiant/Système: ${(_mixLevel * 100).round()}%',
                                style: Theme.of(context).textTheme.titleMedium,
                              ),
                              Row(
                                children: [
                                  const Text('Ambiant'),
                                  Expanded(
                                    child: Slider(
                                      value: _mixLevel,
                                      onChanged: _updateMixLevel,
                                    ),
                                  ),
                                  const Text('Système'),
                                ],
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              );
            }
          }
          EOL

      - name: Install dependencies
        run: flutter pub get
          
      - name: Build APK
        run: |
          flutter build apk --debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
